### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by Pugazhendhi1988** [webepix/webepix.com#3]
The icons "F like","Share ", "G+" (Social media share icons) are not aligned properly in the Footer of  every  webpage. 
![the icons are not aligned properly](https://cloud.githubusercontent.com/assets/9816584/5083736/324f36fe-6f21-11e4-95b0-01d04098f7ab.PNG)

**Comment by Aravin** [comment]
facebook icon removed. @Pugazhendhi1988
